# Generated by Django 3.1 on 2020-08-31 08:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yemek')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yemek')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Resim')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.category', verbose_name='Yemek Kategorisi')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Restaurant İsmi')),
                ('location', models.CharField(max_length=50, verbose_name='Konum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantsFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('score', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('score_count', models.IntegerField(default=0, verbose_name='Puanlayan kişi sayısı')),
                ('total_points', models.IntegerField(default=0)),
                ('missing_points', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.food', verbose_name='Yemek')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.restaurant', verbose_name='Restoran')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200, verbose_name='yorum')),
                ('comment_rate', models.IntegerField(blank=True, default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_missing_rate', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yorum_sahibi')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='system.restaurantsfood')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
